### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by ram-bor** [statisticswithoutborders/swb-app#17]
# Component Name: 
Input

# Details: 
This component will take the following props: size, placeholder, type

<img width="246" alt="Screen Shot 2020-08-21 at 5 17 11 PM" src="https://user-images.githubusercontent.com/66038058/90935886-2dd82a00-e3d2-11ea-9b65-764f6b41bcee.png">

**Comment by allison-johnson** [comment]
@ram-bor , great job so far! A few things to consider before we merge this over to develop:
- You should be using fonts defined in the `font-family` in `index.css`, or talk with Hema about this if you think there are other fonts that should be included.
- To be consistent, use the CSS class name `Input-large` (capital I) since hygen is generating capitalized class names. 
- There should also be an input field for leaving a comment (see Figma mock-up). That should be a **large** input field, as opposed to name, organization, etc., which should be **small** input fields. This also means you need two sizes of input fields -- small and large.

Let me know when you resubmit and I will take another look!
